### ISSUE TITLE
Slow on this one anagram.

### ISSUE THREAD

**Issue by gepoch** [induane/maagnar#1]
Wanted to run a simple test.

I saw on the internet that you can rearrange

"Just because some of us can read and write and do a little math, that doesn't mean we deserve to conquer the universe."

Into

"A masquerade can cover a sense of what is real to deceive us; to be unjaded and not lost, we must, then, determine truth."

I wanted to try it myself, but it's taking a long time to sift through all 7694312863056376945761166215077100371118222304020444562056245684558509344287669013059353201106954038014161121421080471156031488 permutations, and it's taking up all of my RAM.

Please fix.

P.S. It also output this, but I don't know how to speak french. Please also fix.

"J oeeau ooeaseeu,nfi dntsanr.i ttrdt  ttawddsesieeosrn  e   ene laamlttoa rth ru n c ce entmcsbwaeea'qh dm ouvu e hvsd"

**Comment by gepoch** [comment]
Also this one:

"Ennyn Durin Aran Moria. Pedo mellon a minno. Im Narvi hain echant. Celebrimbor o Eregion teithant i thiw hin."

becomes 

"Hi, human idiot. I am main entrance into Dwarven hall. I'm iron; no enemy can enter, nor bribe. I hear thing in pool."

**Comment by induane** [comment]
Hello sir! Please refer to release ``1.0.2`` which is designed to address your important concerns:

Instead of a set, an on-disk FanoutCache is used to determine whether or not a permutation has been seen before. The consumption of memory is no longer an ever-increasing proposition and instead it is disk-space that grows.

Additionally to save precious disk-space, a hash of the permutation is stored rather than the permutation itself. The size of the cache will grow at a constant rate no matter how large the seed string is.

The command line utility now remembers which anagrams you've generated on previous runs, a spectacular new feature made possible by the use of the on-disk cache mechanism.  To start anagram generation over from scratch however, you can use the ``--clear-seen`` command line argument.

**Comment by gepoch** [comment]
Hey I am writing this from the far future. We have invented time travel and also infinitely fast processors, memory, and disks, so some of the problems with the implementation have been solved, but I'm still running into some other problems.

First of all, the hard coded limit of a 1TB cache was just way too small! Fortunately because you've open sourced this python project, I was able to modify it under the terms of the permissive MIT license.

Unfortunately I'm hesitant to continue. Each sha256 hash is 64 bytes. For the full workload I would therefore need 4.92 X 10 ** 113 petabytes. Unfortunately according to the holographic principle this much data would cause the universe to collapse into a black hole expanding outwards at the speed of light, so I'm afraid to run it.

The other problem is that sha256 doesn't have a big enough output size. There will probably be trillions of trillions of collisions, so maagnar isn't even going to print all of the anagrams.

My boss is going to sack me at this rate.

**Comment by gepoch** [comment]
Update: Found a good website for looking up anagrams. Will let you know how it goes: https://libraryofbabel.info/

**Comment by zedr** [comment]
Plz implement this ASAP as I need to ship it tomorrow for an important customer.

**Comment by induane** [comment]
This is a WIP.  I'm implementing hybrid modelling for this. Bear with me.
